version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data --name pgdata
    ports:
      - 5432

  web:
    image: iin
    depends_on:
      - db
    ports:
      - 80:3000
