version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data --name pgdata
    ports:
      - 5432

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports: 6379

  web:
    image: iin
    depends_on:
      - db
      - redis
    ports:
      - 80:3000
